apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-flow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adjust this to match your cluster's storage class