apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-stateless-properties
data:
  stateless.properties: |
    nifi.stateless.props.dir=/opt/nifi/nifi-current/conf
    nifi.stateless.sensitive.props.key=${NIFI_SENSITIVE_PROPS_KEY}
    # Add any other necessary properties here